### ISSUE TITLE
Issues Template

### ISSUE THREAD

**Issue by ranasobeid95** [GSG-G8/art-gallery#1]
# Backend Route template

#### Acceptance Criteria

- [ ]  Validation Schema

- [ ]  Request body

- [ ]  Response

- [ ]  Testing
---
##### Validation schema

---
##### Request body
 ---

##### Response
- Success

```js
{ statusCode:  ,data : { }}
```
- Failed
```js
{statusCode: , message:" "}
```
---

**Comment by ranasobeid95** [comment]
# Frontend  Routes template

### Name should be :  ``` Page name /full-route    ``` 

## Acceptance Criteria
 - [ ] Props
 - [ ] Components
 - [ ] Snapshot

-----------------------------------------------------------------------

### Props

### Components

### Snapshot

**Comment by WessalJawad95** [comment]
> # Backend Route template
> ### Name should be : `METHOD /full-route `
> #### Acceptance Criteria
> * [ ]   Validation Schema
> * [ ]   Request body
> * [ ]   Response
> * [ ]   Testing
> 
> ##### Validation schema
> ##### Request body
> ##### Response
> * Success
> 
> ```js
> { statusCode:  ,data : { }}
> ```
> 
> * Failed
> 
> ```js
> {statusCode: , message:" "}
> ```
> 
> ##### Testing
